### ISSUE TITLE
Rethink ProductPartitioner method design, as it has an issue on AbstractSpatialFunctionPartitioner type

### ISSUE THREAD

**Issue by errearanhas** [JuliaEarth/GeoStatsBase.jl#15]
GeoStatsBase `ProductPartitioner` method (from `product.jl`) is not working properly when two objects of type `AbstractSpatialFunctionPartitioner` are multiplied.

The result is an `AbstractFunctionPartitioner` object, when it should also be `AbstractSpatialFunctionPartitioner`.

**Comment by juliohm** [comment]
This is fixed by https://github.com/JuliaEarth/GeoStatsBase.jl/commit/aff77bccf17607f74590267580d4a18200cd7f68
