### ISSUE TITLE
Update in TableTransforms.jl breaks GeoStatsBase

### ISSUE THREAD

**Issue by veddox** [JuliaEarth/GeoStatsBase.jl#174]
@eliascarv: Due to the removal of `ColSpec` in TableTransforms.jl ([release 1.15.4](https://github.com/JuliaML/TableTransforms.jl/releases/tag/v1.15.4)), I now get the following error with GeoStatsBase:

```
WARNING: could not import TableTransforms.ColSpec into GeoStatsBase
WARNING: could not import TableTransforms.Col into GeoStatsBase
WARNING: could not import TableTransforms.colspec into GeoStatsBase
WARNING: could not import TableTransforms.choose into GeoStatsBase
ERROR: LoadError: UndefVarError: `ColSpec` not defined
```

**Comment by eliascarv** [comment]
Please update your environment to fix this.

**Comment by juliohm** [comment]
@veddox we updated the entire stack recently. Please consider using the main GeoStats.jl module instead:

https://juliaearth.github.io/geospatial-data-science-with-julia/

**Comment by veddox** [comment]
I did `]; update` within my package environment, but GeoStatsBase still refuses to compile. Or did you mean something else?
