### ISSUE TITLE
Possibility of new release soon?

### ISSUE THREAD

**Issue by KristofferC** [JuliaEarth/GeoStatsBase.jl#23]
The latest released version has a bit of old compat info (old RecipesBase for example). It would be great with a new release soon to update these (I see that CompatHelper has done some work in the Project file).

**Comment by juliohm** [comment]
Thank you for the heads up. I'm in the middle of some major changes for a paper, but I think it is possible to release a new version in the following weeks. There are many other packages in the GeoStats.jl stack I think depending on RecipesBase.jl, so I will need more time to assess carefully the upgrade.

**Comment by juliohm** [comment]
Closing it for now, on my radar.
